language: node_js

sudo: false

install:
  - npm install -g babel-cli
  - npm install

services:
  - mongodb

env:
  - TEST_MONGO_ADDR=mongodb://127.0.0.1/mars_mongo_tests

node_js:
  - "5.3"

script: npm test